# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [stg, prod]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-staging:
    if: github.event.action == 'stg'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy to Staging
        env:
          API_COMMIT_HASH: ${{ github.event.client_payload.apiCommitHash }}
          FRONTEND_COMMIT_HASH: ${{ github.event.client_payload.frontendCommitHash }}
          SCHEMA_COMMIT_HASH: ${{ github.event.client_payload.schemaCommitHash }}
        run: |
          echo "Deploying to Staging environment"
          echo "API Commit Hash: $API_COMMIT_HASH"
          echo "Frontend Commit Hash: $FRONTEND_COMMIT_HASH"
          echo "Schema Commit Hash: $SCHEMA_COMMIT_HASH"
      # ここにステージング環境へのデプロイスクリプトを追加

  deploy-production:
    if: github.event.action == 'prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy to Production
        env:
          API_COMMIT_HASH: ${{ github.event.client_payload.apiCommitHash }}
          FRONTEND_COMMIT_HASH: ${{ github.event.client_payload.frontendCommitHash }}
          SCHEMA_COMMIT_HASH: ${{ github.event.client_payload.schemaCommitHash }}
          BRANCH: ${{ github.event.client_payload.branch }}
        run: |
          echo "Deploying to Production environment"
          echo "API Commit Hash: $API_COMMIT_HASH"
          echo "Frontend Commit Hash: $FRONTEND_COMMIT_HASH"
          echo "Schema Commit Hash: $SCHEMA_COMMIT_HASH"
          echo "Branch: $BRANCH"
      # ここに本番環境へのデプロイスクリプトを追加
